name: Generate Plugin Index

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: List files
        run: ls

      - name: Install Index Generator
        run: |
          Invoke-WebRequest -Uri https://github.com/ClassIsland/ClassIsland.PluginIndexGenerator/releases/download/1.1.1.0/ClassIsland.PluginIndexGenerator.zip -OutFile ClassIsland.PluginIndexGenerator.zip
          Expand-Archive -Path ClassIsland.PluginIndexGenerator.zip -DestinationPath .
      
      - name: Generate Plugin Index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir out/source/
          ./ClassIsland.PluginIndexGenerator.exe index/ out/source/ -b base.json -t $env:GITHUB_TOKEN
          7z a "./out/index.zip" ./out/source/* -r -mx=9
          
      - name: Generate MD5
        run: |
          pwsh -ep Bypass -c .\tools\generate-md5.ps1 ./out

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: ./out/*.zip,./out/*.md5sum,./out/source/index.json
          bodyFile: ./out/checksums.md
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload to Alist
        env:
          ALIST_KEY: ${{ secrets.ALIST_KEY }}
          ALIST_HOST: ${{ secrets.ALIST_HOST }}
        run: pwsh -ep bypass ./tools/upload.ps1
